drop table inspection;
drop table violation;
CREATE TABLE inspection(
  SERIAL_NUMBER VARCHAR PRIMARY KEY,
  FACILITY_NAME TEXT,
  FACILITY_ID VARCHAR,
  OWNER_ID VARCHAR NOT NULL, 
  SERVICE_DESCRIPTION TEXT NOT NULL,
  PROGRAM_STATUS VARCHAR NOT NULL
);

CREATE TABLE violation (
   SERIAL_NUMBER VARCHAR PRIMARY KEY,
	FACILITY_NAME TEXT,
   VIOLATION_CODE VARCHAR NOT NULL,
   VIOLATION_STATUS VARCHAR NOT NULL,
   GRADE TEXT
);

SELECT * FROM inspection;

SELECT * FROM violation;

-- Join tables on  SERIAL_NUMBER
SELECT inspection.SERIAL_NUMBER, inspection.FACILITY_ID, inspection.FACILITY_NAME, violation.VIOLATION_CODE, violation.VIOLATION_STATUS
FROM inspection
INNER JOIN violation
ON inspection.SERIAL_NUMBER = violation.SERIAL_NUMBER;